# Generated by Django 4.1.3 on 2022-12-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Title', max_length=100),
            preserve_default=False,
        ),
    ]
